---
apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  annotations:
    gotemplating.fn.crossplane.io/composition-resource-name: namespace
spec:
  forProvider:
    manifest:
      apiVersion: v1
      kind: Namespace
      metadata:
        labels:
          konflux-ci.dev/namespace-type: eaas
  providerConfigRef:
    name: eaas-kubernetes-provider-config

---
apiVersion: meta.gotemplating.fn.crossplane.io/v1alpha1
kind: Context
data:
  namespace: {{ .observed.resources.namespace.resource.metadata.name }}
