name: CI Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Kustomize
        uses: multani/action-setup-kustomize@v1
        with:
          version: 5.1.1

      - name: Run kustomize build
        id: kube-linter-action-scan
        shell: bash
        run: |
          mkdir manifests
          kustomize build --enable-helm crossplane/k8s > manifests/crossplane-k8s.yaml
          kustomize build --enable-helm crossplane/ocp > manifests/crossplane-ocp.yaml
          kustomize build config/k8s > manifests/config-k8s.yaml
          kustomize build config/ocp > manifests/config-ocp.yaml

      # This prepares directory where github/codeql-action/upload-sarif@v1 looks up report files by default.
      - name: Create results directory for SARIF report files
        shell: bash
        run: mkdir -p ../results

      - name: Scan with kube-linter
        uses: stackrox/kube-linter-action@v1.0.4
        with:
          directory: manifests
          format: sarif
          output-file: ../results/kube-linter.sarif
        continue-on-error: true

      - name: Upload SARIF report files to GitHub
        uses: github/codeql-action/upload-sarif@v3

      # Ensure the workflow eventually fails if files did not pass kube-linter checks.
      - name: Verify kube-linter-action succeeded
        shell: bash
        run: |
          echo "If this step fails, kube-linter found issues. Check the output of the scan step above."
          [[ "${{ steps.kube-linter-action-scan.outcome }}" == "success" ]]
